Update TTWInteriors Combo
loot/falloutnv pull request #326
Opened 2023-09-23 18:29 UTC by Superfly-Johnson

I found a conflict between Mothership Zeta Rehaul and TTWInteriors that's easily solveable by just sorting TTWInteriors later. Took the time to also update the entry for it :)

![image](https://github.com/loot/falloutnv/assets/68615650/2f621539-63bf-4ecb-b7fc-71044fa6fbb8)

2023-09-28 14:44 UTC, pStyl3 requested changes

2023-09-28 14:44 UTC, pStyl3 commented on masterlist.yaml
> +      - link: 'https://www.nexusmods.com/newvegas/mods/66449'
Please add a trailing slash `/` at the end of the link.

2023-12-02 19:01 UTC, pStyl3 approved these changes

2024-03-03 09:27 UTC, MacSplody approved these changes

2024-03-03 09:32 UTC, merged

2024-03-03 09:32 UTC, MacSplody commented
Thanks.