Add AWorldOfPainFO3
loot/falloutnv pull request #327
Opened 2023-09-23 23:36 UTC by Superfly-Johnson

Also found an incompatibility with fafnir's unique in xEdit, fixed it and posted the patch, which is also in this commit. Minor stuff, just formid lists needing to be merged. :)

2023-09-25 15:01 UTC, pStyl3 requested changes

2023-09-25 15:01 UTC, pStyl3 commented on masterlist.yaml
> +      - link: 'https://www.nexusmods.com/newvegas/mods/66265'
Please add a trailing slash `/` at the end of the link.

2023-09-25 15:01 UTC, pStyl3 commented on masterlist.yaml
> +          - '[ AWorldOfPainFO3 - FafnirUniqueTTWOverhaul Patch ](https://www.nexusmods.com/newvegas/mods/83169/)'
The empty spaces before and after `AWorldOfPainFO3 - FafnirUniqueTTWOverhaul Patch` (so within the brackets `[ ]`) can be removed.

2023-09-25 18:03 UTC, pStyl3 approved these changes

2024-03-03 09:33 UTC, MacSplody commented on masterlist.yaml
> +    # v2.07
```suggestion
```

2024-03-03 10:21 UTC, MacSplody approved these changes

2024-03-03 10:25 UTC, merged

2024-03-03 10:25 UTC, MacSplody commented
Thanks.