Add Big Town Extensions
loot/falloutnv pull request #328
Opened 2023-09-24 05:09 UTC by Superfly-Johnson

2023-09-25 15:03 UTC, pStyl3 requested changes

2023-09-25 15:03 UTC, pStyl3 commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/newvegas/mods/74825/' ]
Please add the link name to the url.

2023-09-27 05:18 UTC, pStyl3 approved these changes

2023-11-25 19:00 UTC, pStyl3 commented on masterlist.yaml
> +    after: ['AWorldOfPainFO3.esm']
Please add empty spaces like this: `[ 'AWorldOfPainFO3.esm' ]`

2024-03-03 10:25 UTC, MacSplody commented on masterlist.yaml
> +    after: ['AWorldOfPainFO3.esm']
```suggestion
    after: [ 'AWorldOfPainFO3.esm' ]
```

2024-03-03 10:26 UTC, MacSplody commented on masterlist.yaml
> +      # 5.01
```suggestion
```

2024-03-03 10:27 UTC, MacSplody approved these changes

2024-03-03 10:32 UTC, merged

2024-03-03 10:33 UTC, MacSplody commented
Thanks.