Add ROOGNV
loot/falloutnv pull request #334
Opened 2023-09-27 01:54 UTC by Superfly-Johnson

2023-09-27 14:49 UTC, pStyl3 requested changes

2023-09-27 14:49 UTC, pStyl3 commented on masterlist.yaml
> +      - link: 'https://www.nexusmods.com/newvegas/mods/76452'
Please add a trailing slash `/` at the end of the link.

2023-09-28 04:50 UTC, pStyl3 approved these changes

2023-11-26 13:10 UTC, pStyl3 commented on masterlist.yaml
> +      - Scripts
Is the `Scripts` Bash Tag needed here? According to WBs [Advanced Readme](https://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#ScriptsFO3) it refers to changes to the (SCRI) subrecord..

2024-04-04 17:05 UTC, MacSplody commented on masterlist.yaml
> +      - 'WMIMNV.esp'
Master files of a plugin do not need to be added to requirements.
LOOT checks the plugin header and shows an error if any master files are missing.

```suggestion
      - 'WeaponRepairKitRepaired.esp'
```

2024-04-04 17:07 UTC, MacSplody commented on masterlist.yaml
> +      - Scripts
Not required.
```suggestion
```

2024-04-04 17:07 UTC, MacSplody approved these changes

2024-04-04 17:08 UTC, merged