Add Bittercup Companion - Redux
loot/falloutnv pull request #354
Opened 2023-10-03 00:23 UTC by Superfly-Johnson

I think a 

##### NPCs - Followers ##### subsection or something would be nice.

2023-10-03 00:47 UTC, sibir-ine commented
That would be the `Encounters - Allies` section.

2023-10-03 01:03 UTC, Superfly-Johnson commented
Fair enough, I'll update the commit very soon

2023-10-06 04:23 UTC, pStyl3 requested changes

2023-10-06 04:23 UTC, pStyl3 commented on masterlist.yaml
> +      - link: 'https://www.nexusmods.com/newvegas/mods/80781'
Trailing slash `/` is missing.

2023-10-06 04:47 UTC, pStyl3 approved these changes

2023-11-26 07:42 UTC, merged

2023-11-26 07:42 UTC, pStyl3 commented
Thanks!