Adds dirty info for lexx_brahmin-variant.esp and lexx_brahmin-betsy.esp
loot/falloutnv pull request #37
Opened 2018-04-23 19:09 UTC by abiel0530

2018-04-23 19:19 UTC, Ortham commented
CI is failing because you've got the wrong indentation for some fields. E.g.

```
  - name: 'lexx_brahmin-variant.esp'
    dirty:
      - crc: 0xB596767C
      << *dirtyPlugin
      itm: 16
      udr: 1
```

should be 

```
  - name: 'lexx_brahmin-variant.esp'
    dirty:
      - crc: 0xB596767C
        << *dirtyPlugin
        itm: 16
        udr: 1
```

2018-04-23 21:50 UTC, abiel0530 commented
whoops, sorry about that, fixed it

2018-04-24 06:31 UTC, Ortham requested changes

2018-04-24 06:31 UTC, WrinklyNinja commented on masterlist.yaml
> +        << *dirtyPlugin
This needs to be `<<: *dirtyPlugin`, same with line 5337.

2018-04-24 07:11 UTC, SuperSandro2000 commented
@abiel0530 you can do rebase squash localy and force push yourself

2018-04-24 07:14 UTC, WrinklyNinja commented
> @abiel0530 you can do rebase squash localy and force push yourself

It's trivial to squash and merge a PR through GitHub though, and it avoids another round of CI. You can even resolve merge conflicts through the web UI these days, though I find it slightly confusing.

2018-04-24 18:09 UTC, abiel0530 commented
@WrinklyNinja uh, did they squash together nicely? Git says so, after doing the `git rebase` thing

2018-04-24 20:03 UTC, merged